name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        channel: [stable, master]
        run-in: ["workspace", "app"]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}

      - run: flutter widget-preview start
        if: ${{ matrix.run-in }} == "workspace"

      - run: flutter widget-preview start
        if: ${{ matrix.run-in }} == "app"
        working-directory: packages/test
