name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  preview:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        channel: [stable, master]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
          cache: true

      - run: flutter --version

      - run: flutter pub get

      - run: flutter widget-preview start --web-server
        timeout-minutes: 2

  test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        channel: [stable, master]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        if: ${{ matrix.channel == 'master' }}
        with:
          channel: master
          cache: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        if: ${{ matrix.channel != 'master' }}
        with:
          channel: stable
          flutter-version: ${{ matrix.channel }}
          cache: true

      - run: flutter --version

      - run: flutter pub get

      - run: flutter test
        working-directory: packages/asdf
